"""
Two-sample resampling inference for raw continuous samples: a permutation test for the difference
in means (the distribution-free analogue of Welch's t-test) paired with a percentile bootstrap
confidence interval for that difference.

Where Mann–Whitney compares whole distributions through ranks, this pair targets the *mean*
difference directly without assuming normality — the regime where a t-test is the natural estimand
but the normal/​t sampling assumption is shaky (small or skewed samples):

  * Permutation p-value — under the exchangeability null (the arm label carries no information) the
    sampling distribution of the mean-difference statistic is generated by relabelling the pooled
    sample. When the number of distinct label assignments ``C(N, n_t)`` is small enough every one is
    enumerated (an *exact* test); beyond that a fixed-seed Monte Carlo sample of relabellings is
    drawn. The two-sided Monte Carlo p-value uses the add-one estimator
    ``p = (1 + #{|Δ*| ≥ |Δ_obs|}) / (1 + B)``, which keeps the test valid (never reports p = 0).
  * Percentile bootstrap CI — the difference of means is recomputed over ``B`` independent
    with-replacement resamples of each arm; the interval is the empirical ``[α/2, 1−α/2]`` quantiles
    of those replicates.

The p-value tests exchangeability while the interval describes the bootstrap sampling distribution
of the mean difference: they answer slightly different questions and need not agree exactly at the
boundary, so both are surfaced for a complete picture. Resampling is reproducible — a fixed seed
drives the Monte Carlo draws, so identical inputs always yield identical output.

Sources (checked against the literature at implementation time, not from memory): Efron & Tibshirani,
*An Introduction to the Bootstrap* (1993, ch. 13 — the percentile interval); Davison & Hinkley,
*Bootstrap Methods and their Application* (1997, §4 — permutation/randomization tests); Good,
*Permutation, Parametric, and Bootstrap Tests of Hypotheses* (3rd ed.); Phipson & Smyth, "Permutation
P-values Should Never Be Zero" (2010 — the add-one estimator). The module is stdlib-only and holds
pure functions; assembling the response shape lives in the service layer.
"""

import math
from itertools import combinations
from math import comb, isfinite, sqrt
from random import Random
from statistics import NormalDist, fmean, stdev
from typing import Any

_STANDARD_NORMAL = NormalDist()

# Monte Carlo resample count. Inputs are capped at MAX_OBSERVED_SAMPLE_SIZE per arm upstream, so the
# pooled relabelling and per-arm resampling stay cheap at this budget. Small enough samples skip the
# Monte Carlo entirely (exact enumeration below), so this only bites for larger inputs.
DEFAULT_RESAMPLES = 2000

# Fixed seed so the Monte Carlo p-value and bootstrap interval are reproducible for identical inputs.
_DEFAULT_SEED = 20240629


def _bounded_probability(value: float) -> float:
    return min(1.0, max(0.0, value))


def _percentile(sorted_values: list[float], quantile: float) -> float:
    """Linear-interpolation percentile (``quantile`` in [0, 1]) on an already-sorted list."""
    count = len(sorted_values)
    if count == 0:
        raise ValueError("percentile of an empty sequence is undefined")
    if count == 1:
        return sorted_values[0]
    position = quantile * (count - 1)
    lower_index = int(position)
    upper_index = min(lower_index + 1, count - 1)
    fraction = position - lower_index
    return sorted_values[lower_index] + (sorted_values[upper_index] - sorted_values[lower_index]) * fraction


def bootstrap_permutation_test(
    control: list[float],
    treatment: list[float],
    alpha: float = 0.05,
    n_resamples: int = DEFAULT_RESAMPLES,
    seed: int = _DEFAULT_SEED,
) -> dict[str, Any] | None:
    """Permutation test + percentile bootstrap CI for the difference in means on raw samples.

    ``control`` / ``treatment`` are the raw observed values per arm. Returns the observed mean
    difference, the two-sided permutation p-value (exact when ``C(N, n_t) <= n_resamples``, else
    fixed-seed Monte Carlo), the percentile bootstrap CI for that difference, a Welch-based t-like
    statistic with an asymptotic achieved power (descriptive — the inference is resampling-based),
    Cohen's d, the per-arm means and the significance verdict. Returns ``None`` only when an arm is
    empty (the difference is undefined); a fully tied pooled sample is a valid p = 1 result, not a
    degenerate one.
    """
    if not 0 < alpha < 1:
        raise ValueError("alpha must be between 0 and 1")
    if n_resamples < 1:
        raise ValueError("n_resamples must be positive")
    if any(not isfinite(value) for value in control) or any(
        not isfinite(value) for value in treatment
    ):
        raise ValueError("sample values must be finite")

    n_control = len(control)
    n_treatment = len(treatment)
    if n_control < 1 or n_treatment < 1:
        return None

    control_mean = fmean(control)
    treatment_mean = fmean(treatment)
    observed_diff = treatment_mean - control_mean
    abs_observed = abs(observed_diff)

    pooled = control + treatment
    total = n_control + n_treatment
    total_sum = math.fsum(pooled)
    # A permuted statistic numerically equal to the observed one (the identity relabelling is always
    # present in the enumeration) must count as "at least as extreme" despite float rounding.
    tolerance = 1e-9 * (1.0 + abs_observed)

    # --- Permutation p-value: exact enumeration when feasible, else fixed-seed Monte Carlo. ---
    total_assignments = comb(total, n_treatment)
    is_exact = total_assignments <= n_resamples
    at_least_as_extreme = 0
    if is_exact:
        for combo in combinations(pooled, n_treatment):
            subset_sum = math.fsum(combo)
            diff = subset_sum / n_treatment - (total_sum - subset_sum) / n_control
            if abs(diff) >= abs_observed - tolerance:
                at_least_as_extreme += 1
        permutation_count = total_assignments
        # Exact: the identity split is enumerated, so the count is >= 1 and the ratio needs no
        # add-one floor.
        p_value = at_least_as_extreme / permutation_count
    else:
        permutation_rng = Random(seed)
        for _ in range(n_resamples):
            subset_sum = float(sum(permutation_rng.sample(pooled, n_treatment)))
            diff = subset_sum / n_treatment - (total_sum - subset_sum) / n_control
            if abs(diff) >= abs_observed - tolerance:
                at_least_as_extreme += 1
        permutation_count = n_resamples
        p_value = (1 + at_least_as_extreme) / (1 + n_resamples)
    p_value = _bounded_probability(p_value)

    # --- Percentile bootstrap CI for the difference in means. ---
    bootstrap_rng = Random(seed + 1)
    bootstrap_diffs: list[float] = []
    for _ in range(n_resamples):
        treatment_sum = float(sum(bootstrap_rng.choices(treatment, k=n_treatment)))
        control_sum = float(sum(bootstrap_rng.choices(control, k=n_control)))
        bootstrap_diffs.append(treatment_sum / n_treatment - control_sum / n_control)
    bootstrap_diffs.sort()
    ci_lower = _percentile(bootstrap_diffs, alpha / 2.0)
    ci_upper = _percentile(bootstrap_diffs, 1.0 - alpha / 2.0)

    # Cohen's d (pooled-SD standardized mean difference); undefined when the pooled SD collapses.
    cohens_d: float | None = None
    test_statistic = 0.0
    power_achieved = 0.0
    if n_control >= 2 and n_treatment >= 2:
        control_std = stdev(control)
        treatment_std = stdev(treatment)
        pooled_variance = (
            (n_control - 1) * control_std**2 + (n_treatment - 1) * treatment_std**2
        ) / (total - 2)
        if pooled_variance > 0:
            cohens_d = observed_diff / sqrt(pooled_variance)
        # Welch standard error gives a t-like statistic and an asymptotic achieved power, reported in
        # the same shape as the parametric estimators (descriptive only).
        standard_error = sqrt(control_std**2 / n_control + treatment_std**2 / n_treatment)
        if standard_error > 0:
            test_statistic = observed_diff / standard_error
            z_critical = _STANDARD_NORMAL.inv_cdf(1.0 - alpha / 2.0)
            standardized = abs(test_statistic)
            power_achieved = _STANDARD_NORMAL.cdf(standardized - z_critical) + _STANDARD_NORMAL.cdf(
                -z_critical - standardized
            )

    return {
        "control_mean": control_mean,
        "treatment_mean": treatment_mean,
        "observed_diff": observed_diff,
        "p_value": p_value,
        "ci_lower": ci_lower,
        "ci_upper": ci_upper,
        "ci_level": 1.0 - alpha,
        "test_statistic": test_statistic,
        "is_significant": p_value < alpha,
        "power_achieved": _bounded_probability(power_achieved),
        "cohens_d": cohens_d,
        "n_resamples": permutation_count,
        "is_exact": is_exact,
    }
