"""Quantile treatment effect on raw continuous samples: a permutation test for the difference of a
chosen quantile (median by default, but any q) paired with a percentile bootstrap confidence interval
for that quantile difference.

Where the bootstrap/permutation mean test targets the *average* effect, this one targets the effect
at a single point of the distribution — the median, the 90th percentile of latency, the 10th
percentile of revenue. A treatment can leave the mean untouched yet move a tail (compress p99 latency,
lift the bottom decile), and a quantile effect is the estimand that sees it:

  * Permutation p-value — under the exchangeability null (the arm label carries no information about
    the outcome, i.e. the two arms share one distribution) the sampling distribution of the
    quantile-difference statistic ``Q_t(q) − Q_c(q)`` is generated by relabelling the pooled sample.
    When the number of distinct label assignments ``C(N, n_t)`` is small enough every one is
    enumerated (an *exact* test); beyond that a fixed-seed Monte Carlo sample of relabellings is
    drawn. The two-sided Monte Carlo p-value uses the add-one estimator
    ``p = (1 + #{|τ*| ≥ |τ_obs|}) / (1 + B)``, which keeps the test valid (never reports p = 0).
  * Percentile bootstrap CI — the quantile difference is recomputed over ``B`` independent
    with-replacement resamples of each arm; the interval is the empirical ``[α/2, 1−α/2]`` quantiles
    of those replicates.

The p-value tests the sharp exchangeability null with the quantile difference as its statistic, while
the interval describes the bootstrap sampling distribution of that difference: they answer slightly
different questions and need not agree exactly at the boundary, so both are surfaced. Empirical
quantiles use the same linear-interpolation rule the bootstrap module uses, so the median path agrees
with ``statistics.median``. Resampling is reproducible — a fixed seed drives the Monte Carlo draws, so
identical inputs always yield identical output.

Sources (checked against the literature at implementation time, not from memory): Koenker, *Quantile
Regression* (2005 — quantile treatment effects); Efron & Tibshirani, *An Introduction to the
Bootstrap* (1993, ch. 13 — the percentile interval); Davison & Hinkley, *Bootstrap Methods and their
Application* (1997, §4 — permutation/randomization tests); Phipson & Smyth, "Permutation P-values
Should Never Be Zero" (2010 — the add-one estimator). The module is stdlib-only and holds pure
functions; assembling the response shape lives in the service layer.
"""

from itertools import combinations
from math import comb, isfinite
from random import Random
from statistics import NormalDist, stdev
from typing import Any

_STANDARD_NORMAL = NormalDist()

# Monte Carlo resample count. Inputs are capped at MAX_OBSERVED_SAMPLE_SIZE per arm upstream, so the
# pooled relabelling and per-arm resampling stay cheap at this budget. Small enough samples skip the
# Monte Carlo entirely (exact enumeration below), so this only bites for larger inputs.
DEFAULT_RESAMPLES = 2000

# Fixed seed so the Monte Carlo p-value and bootstrap interval are reproducible for identical inputs.
_DEFAULT_SEED = 20240629


def _bounded_probability(value: float) -> float:
    return min(1.0, max(0.0, value))


def _quantile(sorted_values: list[float], quantile: float) -> float:
    """Linear-interpolation quantile (``quantile`` in [0, 1]) on an already-sorted list.

    Matches the rule used by the bootstrap module's percentile helper, so the q = 0.5 path coincides
    with ``statistics.median`` for both even and odd sample sizes.
    """
    count = len(sorted_values)
    if count == 0:
        raise ValueError("quantile of an empty sequence is undefined")
    if count == 1:
        return sorted_values[0]
    position = quantile * (count - 1)
    lower_index = int(position)
    upper_index = min(lower_index + 1, count - 1)
    fraction = position - lower_index
    return sorted_values[lower_index] + (sorted_values[upper_index] - sorted_values[lower_index]) * fraction


def quantile_treatment_effect_test(
    control: list[float],
    treatment: list[float],
    quantile: float = 0.5,
    alpha: float = 0.05,
    n_resamples: int = DEFAULT_RESAMPLES,
    seed: int = _DEFAULT_SEED,
) -> dict[str, Any] | None:
    """Permutation test + percentile bootstrap CI for the difference of the ``quantile``-th quantile.

    ``control`` / ``treatment`` are the raw observed values per arm. Returns the per-arm quantiles, the
    observed quantile difference ``Q_t(q) − Q_c(q)``, the two-sided permutation p-value (exact when
    ``C(N, n_t) <= n_resamples``, else fixed-seed Monte Carlo), the percentile bootstrap CI for that
    difference, a bootstrap-standardized z-like statistic with an asymptotic achieved power
    (descriptive — the inference is resampling-based), and the significance verdict. Returns ``None``
    only when an arm is empty (the difference is undefined); a fully tied pooled sample is a valid
    p = 1 result, not a degenerate one.
    """
    if not 0 < alpha < 1:
        raise ValueError("alpha must be between 0 and 1")
    if not 0 < quantile < 1:
        raise ValueError("quantile must be between 0 and 1 (exclusive)")
    if n_resamples < 1:
        raise ValueError("n_resamples must be positive")
    if any(not isfinite(value) for value in control) or any(
        not isfinite(value) for value in treatment
    ):
        raise ValueError("sample values must be finite")

    n_control = len(control)
    n_treatment = len(treatment)
    if n_control < 1 or n_treatment < 1:
        return None

    control_quantile = _quantile(sorted(control), quantile)
    treatment_quantile = _quantile(sorted(treatment), quantile)
    observed_diff = treatment_quantile - control_quantile
    abs_observed = abs(observed_diff)

    pooled = control + treatment
    total = n_control + n_treatment
    # A permuted statistic numerically equal to the observed one (the identity relabelling is always
    # present in the enumeration) must count as "at least as extreme" despite float rounding.
    tolerance = 1e-9 * (1.0 + abs_observed)

    def _split_diff(treatment_subset: list[float], control_subset: list[float]) -> float:
        return _quantile(sorted(treatment_subset), quantile) - _quantile(
            sorted(control_subset), quantile
        )

    # --- Permutation p-value: exact enumeration when feasible, else fixed-seed Monte Carlo. ---
    total_assignments = comb(total, n_treatment)
    is_exact = total_assignments <= n_resamples
    at_least_as_extreme = 0
    if is_exact:
        indices = range(total)
        for combo in combinations(indices, n_treatment):
            chosen = set(combo)
            treatment_subset = [pooled[i] for i in combo]
            control_subset = [pooled[i] for i in indices if i not in chosen]
            if abs(_split_diff(treatment_subset, control_subset)) >= abs_observed - tolerance:
                at_least_as_extreme += 1
        permutation_count = total_assignments
        # Exact: the identity split is enumerated, so the count is >= 1 and the ratio needs no
        # add-one floor.
        p_value = at_least_as_extreme / permutation_count
    else:
        permutation_rng = Random(seed)
        for _ in range(n_resamples):
            shuffled = permutation_rng.sample(pooled, total)
            if abs(_split_diff(shuffled[:n_treatment], shuffled[n_treatment:])) >= abs_observed - tolerance:
                at_least_as_extreme += 1
        permutation_count = n_resamples
        p_value = (1 + at_least_as_extreme) / (1 + n_resamples)
    p_value = _bounded_probability(p_value)

    # --- Percentile bootstrap CI for the quantile difference. ---
    bootstrap_rng = Random(seed + 1)
    bootstrap_diffs: list[float] = []
    for _ in range(n_resamples):
        treatment_resample = bootstrap_rng.choices(treatment, k=n_treatment)
        control_resample = bootstrap_rng.choices(control, k=n_control)
        bootstrap_diffs.append(_split_diff(treatment_resample, control_resample))
    bootstrap_diffs.sort()
    ci_lower = _quantile(bootstrap_diffs, alpha / 2.0)
    ci_upper = _quantile(bootstrap_diffs, 1.0 - alpha / 2.0)

    # The bootstrap standard error of the quantile difference yields a z-like statistic and an
    # asymptotic achieved power, reported in the same shape as the parametric estimators (descriptive
    # only — the inference is the permutation p-value above). Undefined when the replicates collapse.
    test_statistic = 0.0
    power_achieved = 0.0
    bootstrap_se = stdev(bootstrap_diffs) if len(bootstrap_diffs) >= 2 else 0.0
    if bootstrap_se > 0:
        test_statistic = observed_diff / bootstrap_se
        z_critical = _STANDARD_NORMAL.inv_cdf(1.0 - alpha / 2.0)
        standardized = abs(test_statistic)
        power_achieved = _STANDARD_NORMAL.cdf(standardized - z_critical) + _STANDARD_NORMAL.cdf(
            -z_critical - standardized
        )

    return {
        "quantile": quantile,
        "control_quantile": control_quantile,
        "treatment_quantile": treatment_quantile,
        "observed_diff": observed_diff,
        "p_value": p_value,
        "ci_lower": ci_lower,
        "ci_upper": ci_upper,
        "ci_level": 1.0 - alpha,
        "test_statistic": test_statistic,
        "is_significant": p_value < alpha,
        "power_achieved": _bounded_probability(power_achieved),
        "n_resamples": permutation_count,
        "is_exact": is_exact,
    }
